### ISSUE TITLE
Docker Deploy to Heroku

### ISSUE THREAD

**Issue by corbanb** [fiorix/freegeoip#171] opened 2016-05-04 04:28 UTC
@fiorix thanks so much for the work here. I was curious if you have any thoughts on it not completing the deploy to heroku. Seems fairly straight forward but is failing on the last step. Any thoughts?

``` bash
$  heroku docker:push web
Sending build context to Docker daemon 3.718 MB
Step 1 : FROM golang:1.6
 ---> cc0238ad5a56
Step 2 : COPY cmd/freegeoip/public /var/www
 ---> Using cache
 ---> 7f0ccbba3994
Step 3 : ADD . /go/src/github.com/fiorix/freegeoip
 ---> 4bceab75f4d3
Removing intermediate container 930f9f3a03c1
Step 4 : RUN cd /go/src/github.com/fiorix/freegeoip/cmd/freegeoip && go get && go install
 ---> Running in 174de272a905
 ---> f978685f425f
Removing intermediate container 174de272a905
Step 5 : ENTRYPOINT /go/bin/freegeoip
 ---> Running in be4bed2868e5
 ---> cd2c10cb34c3
Removing intermediate container be4bed2868e5
Step 6 : CMD -use-x-forwarded-for -public /var/www
 ---> Running in 488cbda2d4f0
 ---> 7499b975a383
Removing intermediate container 488cbda2d4f0
Successfully built 7499b975a383
The push refers to a repository [registry.heroku.com/my-app-42324/web]
a448400d5d79: Retrying in 1 seconds
3b40c0d5a2d9: Retrying in 1 seconds
f87a3a003bcd: Retrying in 1 seconds
5d8bfdaba994: Retrying in 1 seconds
5f70bf18a086: Retrying in 1 seconds
39d31a30c667: Retrying in 5 seconds
5da3c7a63a96: Retrying in 5 seconds
0b2fe2c6ef6b: Retrying in 5 seconds
591569fa6c34: Retrying in 5 seconds
998608e2fcd4: Waiting
c12ecfd4861d: Waiting
no basic auth credentials
 !    Error: docker push exited with 1
```

Thanks so much.

**Comment by fiorix** [comment] 2016-05-04 04:33
Looks like docker push failing because of "no basic auth credentials" ? I think you have to use docker login or something like that first.

**Comment by kanekotic** [comment] 2016-09-21 06:52
this should be re open i can confirm its happening to me also and I have login in both services through command line.

**Comment by patrickaroo** [comment] 2016-11-05 18:42
I'm having the same problem after logging in.

**Comment by spencerthayer** [comment] 2016-12-05 15:16
Also having this problem.

**Comment by fiorix** [comment] 2016-12-05 16:00
I haven't used Heroku in a while so no idea what is going on here. If anyone think this is related to how this repo is organised (e.g. because of `cmd/freegeoip` or something along those lines) I'd be happy to review PRs.

**Comment by lenovouser** [comment] 2016-12-05 16:03
This has nothing to do with freegeoip because the container successfully builds. It has something to do with Heroku not being able to push to their own registry. You should open an issue with them.

**Comment by fiorix** [comment] 2016-12-05 16:06
That was my understanding from the original logs, either. If nobody updates this in a week or so I will close it again.

**Comment by fiorix** [comment] 2017-02-16 20:11
We have the "Deploy to Heroku" button now.

**Closed by fiorix** 2017-02-16 20:11 UTC

**Comment by kaiserho** [comment] 2017-05-07 12:51
I no longer have the same issue after logging into the heroku container registry by running `heroku container:login` in the terminal.

**Comment by byteshiva** [comment] 2019-02-15 13:13
I had the same error, ```heroku container:login``` fixed the issue. 

The documentation are [https://devcenter.heroku.com/articles/container-registry-and-runtime](https://devcenter.heroku.com/articles/container-registry-and-runtime) are not updated with latest syntax.

**Here** are the example cli commands to push custome Dockerfile to heroku
```
 heroku login
 heroku container:login
 heroku container:push web --app appname-12389
 heroku container:release web --app appname-12389
```

**Comment by flyingnobita** [comment] 2020-05-05 12:09
https://devcenter.heroku.com/articles/container-registry-and-runtime#logging-in-to-the-registry

According to the latest heroku doc, one needs to login to the Container Registry otherwise `heroku container:push` will fail with error: `no basic auth credentials`.
